seed: 0
exp:
  run: 'random-5-imagenette-woof'
  num_epochs: 100
  debug: false
  wandb: true

model:
  resume: false

data:
  dataset: 'ImagenetteWoof'
  test_dataset: 'ImagenetteWoof'
  batch_size: 256
  root: '/shared/lisabdunlap/data'

hps:
  lr: 0.001
  weight_decay: 5e-5

noise:
  p: 0.05
  method: random
  # clean_val: false