exp:
  run: expanded_imagenette-noisy-10

data:
  dataset: ExpandedImagenette
  test_dataset: ExpandedImagenette
  batch_size: 256

model:
  arch: resnet18

noise:
  p: 0.1
  method: confusion_matrix
  clean_val: false
  confusion_matrix: predictions/ExpandedImagenette/confusion_matrix.npy
  # confusion_matrix: predictions/ExpandedImagenette/imagenette_combined_full/all/conf_matrix.npy

hps:
  lr: 0.01