proj: dynamic-weighting-domainnet
exp:
  run: domainnet-v1

data: 
  dataset: DomainNetV1
  test_dataset: DomainNetV1
  batch_size: 256

model:
  arch: resnet50
  ft: true
  save_emb: true
  
hps:
  optimizer: adam