proj: dynamic_weighting-food101
exp:
  run: 'food101'
  num_epochs: 200

model:
  arch: resnet50
  ft: true
  save_emb: true
  load_emb: true

data:
  dataset: 'Food101'
  test_dataset: 'Food101'
  train_first_split: 'even'

hps:
  lr: 0.01