seed: 0
exp:
  run: 'imagenette'
  num_epochs: 200
  debug: false
  wandb: true

model:
  resume: false

data:
  dataset: 'Imagenette'
  test_dataset: 'Imagenette'
  batch_size: 256
  root: '/shared/lisabdunlap/data'

hps:
  lr: 0.001
  weight_decay: 5e-5

noise:
  p: 0.00
  method: noop
  clean_val: false