seed: 0
exp:
  run: 'clean'
  num_epochs: 200
  debug: false
  wandb: true
  train_first_split_only: false

model:
  resume: false
  ft: false
  save_every: 1
  resume_epoch: 'best'
  eval: false

data:
  dataset: 'Waterbirds100'
  train_first_split: 'even'
  test_dataset: 'Waterbirds'
  batch_size: 256
  root: '/shared/lisabdunlap/data'
  imagenetc_corruption: 'glass_blur'
  remove: false
  num_samples_to_remove: 0.1 # could either be a proportion or a set number
  removal_method: random

hps:
  lr: 0.001
  weight_decay: 5e-5

noise:
  p: 0.1
  method: noop
  clean_val: false