seed: 0
exp:
  run: 'clean'
  num_epochs: 200
  debug: false
  wandb: true

model:
  resume: false
  ft: false
  save_every: 1
  resume_epoch: 'best'

data:
  dataset: 'Waterbirds'
  train_first_split: 'even'
  test_dataset: 'Waterbirds'
  batch_size: 256
  root: '/shared/lisabdunlap/vl-attention/data'
  imagenetc_corruption: 'glass_blur'

hps:
  lr: 0.001
  weight_decay: 5e-5

noise:
  p: 0.1
  method: noop
  clean_val: false