exp:
  run: waterbirds95
  class_weights: false

data:
  dataset: Waterbirds95
  test_dataset: Waterbirds95
  root: '/shared/lisabdunlap/vl-attention/data'
  upweight_factor: 5

model:
  arch: resnet50
  ft: true
  save_emb: true

hps:
  lr: 0.01