exp:
  run: waterbirds95-sanity
  class_weights: true

data:
  dataset: Waterbirds95
  test_dataset: Waterbirds95
  root: '/shared/lisabdunlap/vl-attention/data'

model:
  arch: resnet50
  ft: true
  save_emb: true